package exceptions;

public enum ErrorType {
	GENERAL_ERROR, 
	NAME_ALREADY_EXISTS,
	INVALID_COMPANY,
	INVALID_AMOUNT_VALUE,
	INVALID_PRICE_VALUE,
	INVALID_STRING,
	INVALID_START_AND_END_DATES, 
	INVALID_END_DATE, 
	ID_DONT_EXIST
	

}
